name: build onecloud image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          # 这个值是保留给系统的空间大小，之前设置太小，总会在安装依赖或者编译过程中报设备空间不足的错误而导致编译失败
          root-reserve-mb: 18096
          swap-size-mb: 2266
          remove-dotnet: 'true'
          remove-android: 'true'
      
      - name: Checkout armbian/build
        run: |
          git clone https://github.com/witallwang/Build-Armbian
          
      - name: Build for onecloud
        run: |
          cd Build-Armbian
          ./compile.sh BOARD="odroidxu4" BRANCH="current" RELEASE="bullseye" KERNEL_ONLY="no" KERNEL_CONFIGURE="no" BUILD_DESKTOP="no" BUILD_MINIMAL="yes"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.RELEASE }}-${{ matrix.BRANCH }}-${{ matrix.TYPE == 'desktop' && matrix.DESKTOP_ENVIRONMENT || matrix.TYPE }}
          path: output/images/*

  release:
    needs: [ prepare, build ]
    runs-on: ubuntu-22.04
    steps:
      - name: Import env
        run: |
          echo "$(echo "${{ needs.prepare.outputs.env }}" | base64 -d)" >>$GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Generate sha256sum
        run: |
          touch sha256sum
          for a in artifacts/*/*.sha; do
            cat "$a" >>sha256sum
            rm -f "$a"
          done

      - name: Show sha256sum
        run: |
          cat sha256sum

          cat <<EOF | sed -E 's/^  //' >>$GITHUB_STEP_SUMMARY
            # SHA256
            $(cat sha256sum | awk '{printf "%s: `%s`\n", $2, $1}')
          EOF

      - name: Release
        run: |
          cat <<EOF | sed -E 's/^  //' >Release.md
            CI $(date -d "$TIME" +'%Y-%m-%d %H:%M:%S %Z(%:z)')

            # Sources
            Script: [${SCRIPT_REPO}@${SCRIPT_REF}](https://github.com/${SCRIPT_REPO}/tree/${SCRIPT_REF}) ([\`${SCRIPT_SHA}\`](https://github.com/${SCRIPT_REPO}/tree/${SCRIPT_SHA}))
            U-Boot: [${UBOOT_REPO}@${UBOOT_RELEASE}](https://github.com/${UBOOT_REPO}/releases/tag/${UBOOT_RELEASE}) ([\`${UBOOT_TAG}\`](https://github.com/${UBOOT_REPO}/releases/tag/${UBOOT_TAG}))
            Armbian: [${ARMBIAN_REPO}@${ARMBIAN_REF}](https://github.com/${ARMBIAN_REPO}/tree/${ARMBIAN_REF}) ([\`${ARMBIAN_SHA}\`](https://github.com/${ARMBIAN_REPO}/tree/${ARMBIAN_SHA}))

            # SHA256
            $(cat sha256sum | awk '{printf "%s: `%s`\n", $2, $1}')
          EOF

          tag="ci-$(date -d "$TIME" -u +'%Y%m%d-%H%M%S-%Z')"
          hub release create  -t "$GITHUB_SHA" "$tag" -F Release.md \
            -a sha256sum \
            $(for a in artifacts/*/Armbian_*; do echo -a $a; done) \
            $(for a in artifacts/*/linux-{image,headers,dtb}-*; do echo -a $a; done)
        env:
          GITHUB_TOKEN: ${{ github.token }}
